# Generated by Django 5.2.4 on 2025-07-19 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=9)),
                ('student_type', models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура')], default='bachelor', max_length=20)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.universitymodel')),
            ],
        ),
    ]
