# Generated by Django 5.2.4 on 2025-07-19 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=9)),
                ('sponsor_type', models.CharField(default='physical', verbose_name=[('physical', 'Физическое лицо'), ('legal', 'Юридическое лицо')])),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsored_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('spend_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(default='new', verbose_name=[('new', 'Новый'), ('confirmed', 'Подтверждённый'), ('canceled', 'Отменённый'), ('moderation', 'В модернизации')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'db_table': 'Sponsors',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorToStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_links', to='sponsors.sponsormodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='students.studentmodel')),
            ],
        ),
    ]
