# Generated by Django 5.2.4 on 2025-07-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsormodel',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждённый'), ('canceled', 'Отменённый'), ('moderation', 'В модернизации')], default='new'),
        ),
    ]
