# Generated by Django 5.2.4 on 2025-07-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsormodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsormodel',
            name='sponsor_type',
            field=models.CharField(choices=[('physical', 'Физическое лицо'), ('legal', 'Юридическое лицо')], default='physical'),
        ),
    ]
